[package]
name = "recorder"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
tokio = { version = "1.35.0", features = ["sync", "process", "rt"] }
tracing = "0.1.40"
wav = "1.0.0"
