[package]
name = "bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nn = { path = "../nn" }
dashmap = "5.5.3"
futures = "0.3.28"
rand = "0.8.5"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
serde_with = "3.4.0"
serenity = { version = "0.11.7", default-features = false, features = [
    "builder",
    "cache",
    "time",
    "client",
    "gateway",
    "model",
    "http",
    "utils",
    "voice",
] }
songbird = { version = "0.3.2", features = ["tokio"] }
thiserror = "1.0.50"
time = { version = "0.3.30", features = ["serde", "serde-well-known"] }
tokio = { version = "1.33.0", features = ["full"] }
tokio-tungstenite = "0.20.1"
toml = "0.8.4"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[features]
default = ["cuda", "cudnn"]
cuda = ["nn/cuda"]
cudnn = ["nn/cudnn"]
